### ISSUE TITLE
Support text attributes?

### ISSUE THREAD

**Issue by orih** [neocotic/html.md#51]
Is there any plan to support text attributes like bold, italic, strikethrough?

**Comment by neocotic** [comment]
Can you elaborate more on what you mean by "text attributes"? Perhaps providing an example of input and the output you'd expect/desire?

**Comment by orih** [comment]
Here is an example below from [Wikipedia](http://en.wikipedia.org/wiki/Markdown) which linked in [README.md](https://github.com/neocotic/html.md/blob/master/README.md)

Input:
```
Text attributes <em>italic</em>, <strong>bold</strong>,
<code>monospace</code>, <s>strikethrough</s>.
```

Output:
```
Text attributes *italic*, **bold**,
 `monospace`, ~~strikethrough~~ .
```

**Comment by neocotic** [comment]
And which of these are you having a problem with? The only one that's not already support is strikethrough (i.e. `<s>`) since that is not supported by pure Markdown as far as I'm aware.

What are you seeing happen when you attempt to convert the input you've provided with html.md?

**Comment by orih** [comment]
> The only one that's not already support is strikethrough (i.e. `<s>`)
My test data was not correct, and yes, it's exactly working properly without `<s>` which I expected to be converted. Could you share the documentation page or an url you mentioned as pure Markdown?

**Comment by neocotic** [comment]
Good stuff. I'll close this issue then.

Here's the official homepage of the original Markdown language:

http://daringfireball.net/projects/markdown/

**Comment by orih** [comment]
Thanks :)
